version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env.docker
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env.docker
    command: >
        sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"

volumes:
  db_data: