"""add photo_path

Revision ID: 3b031be2ee8c
Revises: a106b201c7b4
Create Date: 2025-09-17 16:20:35.996289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b031be2ee8c'
down_revision: Union[str, None] = 'a106b201c7b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('photo_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'photo_path')
    # ### end Alembic commands ###
